// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvHGIPPqgHDWvB3JiiHg9FtH2m5nZMR2k',
    appId: '1:25194491712:android:6eeb59a88e88e081d8d4a5',
    messagingSenderId: '25194491712',
    projectId: 'mytestf-6c08c',
    databaseURL: 'https://mytestf-6c08c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mytestf-6c08c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMNctoTQHfZy3mBdzCS-lpGJ3zDXr30es',
    appId: '1:25194491712:ios:33f0fff7a1fe6804d8d4a5',
    messagingSenderId: '25194491712',
    projectId: 'mytestf-6c08c',
    databaseURL: 'https://mytestf-6c08c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mytestf-6c08c.appspot.com',
    androidClientId: '25194491712-03eo2nqq5mngr2qb2mgcjrra65nj3jns.apps.googleusercontent.com',
    iosClientId: '25194491712-g0idndiub95kjphsr7asuba0gr9n8ife.apps.googleusercontent.com',
    iosBundleId: 'com.example.dateapp',
  );
}
